# Generated by Django 5.1.7 on 2025-03-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kandamul', '0004_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='name',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
