# Generated by Django 5.1.7 on 2025-03-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kandamul', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='From the Heart of the Himalayas', max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
